import { Noto_Sans_KR } from "next/font/google";
import Providers from "@/utils/provider";
import "../styles/global.scss";
import { DialogProvider } from "@/context/DialogContext";
import { getMyAccount } from "@/lib/api/me";
import { UserProvider } from "@/context/userContext";

export const metadata = {
  title: "mz",
  description: "Generated by create next app",
};

// const notoSans = Noto_Sans_KR({
//   weight: ["400", "500", "700"],
//   subsets: ["latin"],
//   display: "swap",
// });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // 캐시되어있어서 그런가??
  const user = await getMyAccount();
  console.log("RootLayout", user);
  return (
    <html lang="en">
      <body>
        <Providers>
          <DialogProvider>
            <UserProvider user={user}>{children}</UserProvider>
          </DialogProvider>
        </Providers>
      </body>
    </html>
  );
}
