import { Noto_Sans_KR } from "next/font/google";
import Providers from "@/utils/provider";
import "../styles/global.scss";
import { DialogProvider } from "@/context/DialogContext";

export const metadata = {
  title: "mz",
  description: "Generated by create next app",
};

const notoSans = Noto_Sans_KR({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <Providers>
          <DialogProvider>{children}</DialogProvider>
        </Providers>
      </body>
    </html>
  );
}
