import TabLayout from "@/components/layout/TabLayout";
import { getBookmarks } from "@/lib/api/bookmark";
import styles from "@/styles/StyledTabLayout.module.scss";
import getQueryClient from "@/utils/getQueryClient";
import Hydrate from "@/utils/hydrate.client";
import { dehydrate } from "@tanstack/react-query";

export const metadata = {
  title: "bookmark",
  description: "Generated by create next app",
};

export default async function Root({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClient = getQueryClient();
  const dehydratedState = dehydrate(queryClient);
  await queryClient.prefetchInfiniteQuery(["bookmarks"], () => getBookmarks());

  return (
    <Hydrate state={dehydratedState}>
      <TabLayout className={styles.layout_padding}>
        <div className={styles.content}>{children}</div>
      </TabLayout>
    </Hydrate>
  );
}
