import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  // regionCategory 초기 데이터 추가
  await prisma.regionCategory.createMany({
    data: [
      { name: '서울' },
      { name: '부산' },
      { name: '대구' },
      { name: '인천' },
      { name: '광주' },
      { name: '대전' },
      { name: '울산' },
      { name: '세종' },
      { name: '경기' },
      { name: '강원' },
      { name: '충북' },
      { name: '충남' },
      { name: '전북' },
      { name: '전남' },
      { name: '경북' },
      { name: '경남' },
      { name: '제주' },
      { name: '전체' },
      // 다른 지역 정보도 추가
    ],
  })

  // area 초기 데이터 추가
  await prisma.area.createMany({
    data: [
      { name: '강남구', regionCategoryId: 1 },
      { name: '강동구', regionCategoryId: 1 },
      { name: '강북구', regionCategoryId: 1 },
      { name: '강서구', regionCategoryId: 1 },
      { name: '관악구', regionCategoryId: 1 },
      { name: '광진구', regionCategoryId: 1 },
      { name: '구로구', regionCategoryId: 1 },
      { name: '금천구', regionCategoryId: 1 },
      { name: '노원구', regionCategoryId: 1 },
      { name: '도봉구', regionCategoryId: 1 },
      { name: '동대문구', regionCategoryId: 1 },
      { name: '동작구', regionCategoryId: 1 },
      { name: '마포구', regionCategoryId: 1 },
      { name: '서대문구', regionCategoryId: 1 },
      { name: '서초구', regionCategoryId: 1 },
      { name: '성동구', regionCategoryId: 1 },
      { name: '성북구', regionCategoryId: 1 },
      { name: '송파구', regionCategoryId: 1 },
      { name: '양천구', regionCategoryId: 1 },
      { name: '영등포구', regionCategoryId: 1 },
      { name: '용산구', regionCategoryId: 1 },
      { name: '은평구', regionCategoryId: 1 },
      { name: '종로구', regionCategoryId: 1 },
      { name: '중구', regionCategoryId: 1 },
      { name: '중랑구', regionCategoryId: 1 },
      { name: '강서구', regionCategoryId: 2 },
      { name: '금정구', regionCategoryId: 2 },
      { name: '기장군', regionCategoryId: 2 },
      { name: '남구', regionCategoryId: 2 },
      { name: '동구', regionCategoryId: 2 },
      { name: '동래구', regionCategoryId: 2 },
      { name: '부산진구', regionCategoryId: 2 },
      { name: '북구', regionCategoryId: 2 },
      { name: '사상구', regionCategoryId: 2 },
      { name: '사하구', regionCategoryId: 2 },
      { name: '서구', regionCategoryId: 2 },
      { name: '수영구', regionCategoryId: 2 },
      { name: '연제구', regionCategoryId: 2 },
      { name: '영도구', regionCategoryId: 2 },
      { name: '중구', regionCategoryId: 2 },
      { name: '해운대구', regionCategoryId: 2 },
      { name: '남구', regionCategoryId: 3 },
      { name: '달서구', regionCategoryId: 3 },
      { name: '달성군', regionCategoryId: 3 },
      { name: '동구', regionCategoryId: 3 },
      { name: '북구', regionCategoryId: 3 },
      { name: '서구', regionCategoryId: 3 },
      { name: '수성구', regionCategoryId: 3 },
      { name: '중구', regionCategoryId: 3 },
      { name: '군위군', regionCategoryId: 3 },
      { name: '강화군', regionCategoryId: 4 },
      { name: '계양구', regionCategoryId: 4 },
      { name: '미추홀구', regionCategoryId: 4 },
      { name: '남동구', regionCategoryId: 4 },
      { name: '동구', regionCategoryId: 4 },
      { name: '부평구', regionCategoryId: 4 },
      { name: '서구', regionCategoryId: 4 },
      { name: '연수구', regionCategoryId: 4 },
      { name: '옹진군', regionCategoryId: 4 },
      { name: '중구', regionCategoryId: 4 },
      { name: '광산구', regionCategoryId: 5 },
      { name: '남구', regionCategoryId: 5 },
      { name: '동구', regionCategoryId: 5 },
      { name: '북구', regionCategoryId: 5 },
      { name: '서구', regionCategoryId: 5 },
      { name: '대덕구', regionCategoryId: 6 },
      { name: '동구', regionCategoryId: 6 },
      { name: '서구', regionCategoryId: 6 },
      { name: '유성구', regionCategoryId: 6 },
      { name: '중구', regionCategoryId: 6 },
      { name: '중구', regionCategoryId: 7 },
      { name: '남구', regionCategoryId: 7 },
      { name: '동구', regionCategoryId: 7 },
      { name: '북구', regionCategoryId: 7 },
      { name: '울주군', regionCategoryId: 7 },
      { name: '세종시', regionCategoryId: 8 },
      { name: '가평군', regionCategoryId: 9 },
      { name: '고양시', regionCategoryId: 9 },
      { name: '과천시', regionCategoryId: 9 },
      { name: '광명시', regionCategoryId: 9 },
      { name: '광주시', regionCategoryId: 9 },
      { name: '구리시', regionCategoryId: 9 },
      { name: '군포시', regionCategoryId: 9 },
      { name: '김포시', regionCategoryId: 9 },
      { name: '남양주시', regionCategoryId: 9 },
      { name: '동두천시', regionCategoryId: 9 },
      { name: '부천시', regionCategoryId: 9 },
      { name: '성남시', regionCategoryId: 9 },
      { name: '수원시', regionCategoryId: 9 },
      { name: '시흥시', regionCategoryId: 9 },
      { name: '안산시', regionCategoryId: 9 },
      { name: '안성시', regionCategoryId: 9 },
      { name: '안양시', regionCategoryId: 9 },
      { name: '양주시', regionCategoryId: 9 },
      { name: '양평군', regionCategoryId: 9 },
      { name: '여주시', regionCategoryId: 9 },
      { name: '연천군', regionCategoryId: 9 },
      { name: '오산시', regionCategoryId: 9 },
      { name: '용인시', regionCategoryId: 9 },
      { name: '의왕시', regionCategoryId: 9 },
      { name: '의정부시', regionCategoryId: 9 },
      { name: '이천시', regionCategoryId: 9 },
      { name: '파주시', regionCategoryId: 9 },
      { name: '평택시', regionCategoryId: 9 },
      { name: '포천시', regionCategoryId: 9 },
      { name: '하남시', regionCategoryId: 9 },
      { name: '화성시', regionCategoryId: 9 },
      { name: '강릉시', regionCategoryId: 10 },
      { name: '고성군', regionCategoryId: 10 },
      { name: '동해시', regionCategoryId: 10 },
      { name: '삼척시', regionCategoryId: 10 },
      { name: '속초시', regionCategoryId: 10 },
      { name: '양구군', regionCategoryId: 10 },
      { name: '양양군', regionCategoryId: 10 },
      { name: '영월군', regionCategoryId: 10 },
      { name: '원주시', regionCategoryId: 10 },
      { name: '인제군', regionCategoryId: 10 },
      { name: '정선군', regionCategoryId: 10 },
      { name: '철원군', regionCategoryId: 10 },
      { name: '춘천시', regionCategoryId: 10 },
      { name: '태백시', regionCategoryId: 10 },
      { name: '평창군', regionCategoryId: 10 },
      { name: '홍천군', regionCategoryId: 10 },
      { name: '화천군', regionCategoryId: 10 },
      { name: '횡성군', regionCategoryId: 10 },
      { name: '괴산군', regionCategoryId: 11 },
      { name: '단양군', regionCategoryId: 11 },
      { name: '보은군', regionCategoryId: 11 },
      { name: '영동군', regionCategoryId: 11 },
      { name: '옥천군', regionCategoryId: 11 },
      { name: '음성군', regionCategoryId: 11 },
      { name: '제천시', regionCategoryId: 11 },
      { name: '진천군', regionCategoryId: 11 },
      { name: '청주시', regionCategoryId: 11 },
      { name: '충주시', regionCategoryId: 11 },
      { name: '증평군', regionCategoryId: 11 },
      { name: '공주시', regionCategoryId: 12 },
      { name: '금산군', regionCategoryId: 12 },
      { name: '논산시', regionCategoryId: 12 },
      { name: '당진시', regionCategoryId: 12 },
      { name: '보령시', regionCategoryId: 12 },
      { name: '부여군', regionCategoryId: 12 },
      { name: '서산시', regionCategoryId: 12 },
      { name: '서천군', regionCategoryId: 12 },
      { name: '아산시', regionCategoryId: 12 },
      { name: '예산군', regionCategoryId: 12 },
      { name: '고창군', regionCategoryId: 13 },
      { name: '군산시', regionCategoryId: 13 },
      { name: '김제시', regionCategoryId: 13 },
      { name: '남원시', regionCategoryId: 13 },
      { name: '무주군', regionCategoryId: 13 },
      { name: '부안군', regionCategoryId: 13 },
      { name: '순창군', regionCategoryId: 13 },
      { name: '완주군', regionCategoryId: 13 },
      { name: '익산시', regionCategoryId: 13 },
      { name: '임실군', regionCategoryId: 13 },
      { name: '장수군', regionCategoryId: 13 },
      { name: '전주시', regionCategoryId: 13 },
      { name: '정읍시', regionCategoryId: 13 },
      { name: '진안군', regionCategoryId: 13 },
      { name: '강진군', regionCategoryId: 14 },
      { name: '고흥군', regionCategoryId: 14 },
      { name: '곡성군', regionCategoryId: 14 },
      { name: '광양시', regionCategoryId: 14 },
      { name: '구례군', regionCategoryId: 14 },
      { name: '나주시', regionCategoryId: 14 },
      { name: '담양군', regionCategoryId: 14 },
      { name: '목포시', regionCategoryId: 14 },
      { name: '무안군', regionCategoryId: 14 },
      { name: '보성군', regionCategoryId: 14 },
      { name: '순천시', regionCategoryId: 14 },
      { name: '신안군', regionCategoryId: 14 },
      { name: '여수시', regionCategoryId: 14 },
      { name: '영광군', regionCategoryId: 14 },
      { name: '영암군', regionCategoryId: 14 },
      { name: '완도군', regionCategoryId: 14 },
      { name: '장성군', regionCategoryId: 14 },
      { name: '장흥군', regionCategoryId: 14 },
      { name: '진도군', regionCategoryId: 14 },
      { name: '함평군', regionCategoryId: 14 },
      { name: '해남군', regionCategoryId: 14 },
      { name: '화순군', regionCategoryId: 14 },
      { name: '경산시', regionCategoryId: 15 },
      { name: '경주시', regionCategoryId: 15 },
      { name: '고령군', regionCategoryId: 15 },
      { name: '구미시', regionCategoryId: 15 },
      { name: '김천시', regionCategoryId: 15 },
      { name: '문경시', regionCategoryId: 15 },
      { name: '봉화군', regionCategoryId: 15 },
      { name: '상주시', regionCategoryId: 15 },
      { name: '성주군', regionCategoryId: 15 },
      { name: '안동시', regionCategoryId: 15 },
      { name: '영덕군', regionCategoryId: 15 },
      { name: '영양군', regionCategoryId: 15 },
      { name: '영주시', regionCategoryId: 15 },
      { name: '영천시', regionCategoryId: 15 },
      { name: '예천군', regionCategoryId: 15 },
      { name: '울릉군', regionCategoryId: 15 },
      { name: '울진군', regionCategoryId: 15 },
      { name: '의성군', regionCategoryId: 15 },
      { name: '청도군', regionCategoryId: 15 },
      { name: '청송군', regionCategoryId: 15 },
      { name: '칠곡군', regionCategoryId: 15 },
      { name: '포항시', regionCategoryId: 15 },
      { name: '거제시', regionCategoryId: 16 },
      { name: '거창군', regionCategoryId: 16 },
      { name: '고성군', regionCategoryId: 16 },
      { name: '김해시', regionCategoryId: 16 },
      { name: '남해군', regionCategoryId: 16 },
      { name: '밀양시', regionCategoryId: 16 },
      { name: '사천시', regionCategoryId: 16 },
      { name: '산청군', regionCategoryId: 16 },
      { name: '양산시', regionCategoryId: 16 },
      { name: '의령군', regionCategoryId: 16 },
      { name: '진주시', regionCategoryId: 16 },
      { name: '창녕군', regionCategoryId: 16 },
      { name: '창원시', regionCategoryId: 16 },
      { name: '통영시', regionCategoryId: 16 },
      { name: '하동군', regionCategoryId: 16 },
      { name: '함안군', regionCategoryId: 16 },
      { name: '함양군', regionCategoryId: 16 },
      { name: '합천군', regionCategoryId: 16 },
      { name: '서귀포시', regionCategoryId: 17 },
      { name: '제주시', regionCategoryId: 17 },
    ],
  })
}

main()
  .catch((e) => {
    throw e
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
